// src/lib/strings/publish.ts

export const publishStrings = {
  kicker: "Prepare & publish",
  title: "GitHub & on-chain publication",
  lead:
    "Open a PR on intuition-box/ideas, then attest this brainstorm variant on-chain. Each variant gets its own atom (unique IPFS + explorer link) even when the display title matches a catalog idea.",
  tabs: {
    overview: "Overview",
    github: "GitHub",
    onchain: "On-chain",
    preview: "Preview",
  },
  draftNotice:
    "New draft: catalog state is not indexed yet. The PR will use the refined content above.",
  statusTitle: "GitHub & on-chain status",
  checking: "Checking…",
  loadFailed: "Could not load status.",
  scoped: "Scoped",
  githubPr: "GitHub PR",
  atomIndexed: "Atom indexed",
  coreTriple: "Core triple",
  yes: "Yes",
  no: "No",
  complete: "Complete",
  toCreate: "To create",
  semanticPlan: "Semantic plan",
  actions: "Actions",
  openGithubPr: "Open GitHub PR",
  connectGithubHint: "Connect GitHub in the GitHub tab to enable PR creation.",
  copyMarkdown: "Copy Markdown",
  onchainTitle: "On-chain publication",
  onchainLead:
    'Publish this brainstorm variant for "{title}" on {network}. Each publish uses your current draft and PR link to build a unique on-chain atom and core triple.',
  estimatingCost: "Estimating cost…",
  estimatedCost: "Estimated cost",
  serverWallet: "Server wallet",
  configured: "Configured",
  missing: "Missing",
  existingAtom: "This variant on-chain",
  previewUnavailable: "On-chain preview unavailable.",
  verifyOnchain: "Verify on-chain",
  publishOnchain: "Publish variant on-chain",
  variantAlreadyOnchain:
    "This exact brainstorm variant (draft + PR link) is already attested on-chain.",
  variantReady: "New variant ready to attest on-chain.",
  predictedTermsTitle: "Predicted term IDs (this variant)",
  predictedTermsLead:
    "Derived from your draft + PR link. Different brainstorms around the same catalog idea get different IDs and explorer URLs.",
  predictedIdeaAtom: "Idea atom · term ID",
  predictedCoreTriple: "Core triple · term ID",
  predictedIpfs: "IPFS payload",
  predictedPrLink: "PR link in atom metadata",
  ipfsPending: "Pinning on preview…",
  prLinkMissing: "Open a GitHub PR first to embed the link in metadata.",
  termIdPending: "Could not resolve yet — fix blockers above.",
  termAlreadyOnchain: "On-chain",
  termWillCreate: "Will create",
  copyTermId: "Copy term ID",
  viewTermExplorer: "View on explorer →",
  blockedExistingName: 'Blocked: an atom already uses the name "{title}".',
  readmePreview: "README preview (PR)",
  viewAtomExplorer: "View atom on explorer →",
  openPrGithub: "Open PR on GitHub →",
  createFileGithub: "Create file on GitHub (browser) →",
  startAnotherIdea: "Start another project",
  markdownCopied: "Markdown copied to clipboard.",
  openingPr: "Opening a PR on intuition-box/ideas…",
  apiUnreachable: "Could not reach the publish API.",
  invalidResponse: "Invalid server response.",
  githubLoginRequired: "GitHub login required.",
  prCreated: "PR created on intuition-box/ideas.",
  manualPr: "Automatic PR not configured — Markdown copied.",
  prFailedCopied: "Automatic PR failed — Markdown copied.",
  ideaNotFound: "Idea not found for PR.",
  githubApiFailed: "GitHub API failed.",
  publishBlocked: "Publication blocked — atom already exists under this name.",
  publishing: "Publishing on-chain…",
  publishFailed: "On-chain publication failed.",
  alreadyComplete: "This brainstorm variant is already on-chain.",
  publishSuccess: "On-chain publication succeeded.",
  onchainApiUnreachable: "Could not reach the on-chain API.",
} as const;

export const verificationStrings = {
  loading: 'Checking on-chain name "{name}"…',
  slowHint: " (GraphQL indexer, may take ~10 s)",
  errorPrefix: "On-chain check:",
  retry: "Retry",
  fetchFailed:
    "Could not reach the API (network or server still compiling). Try again in a few seconds.",
  unknownError: "Unknown error",
  verificationFailed: "Verification failed",
  exactMatch: "Same title on graph — variant publish allowed",
  similarNames: "Similar names on the graph",
  nameAvailable: "Name available on-chain",
  viewExplorer: "View on explorer →",
  coreTripleTag: " · core triple",
} as const;

export const githubStrings = {
  checkingSession: "Checking GitHub session…",
  oauthNotConfigured:
    "GitHub OAuth is not configured on the server ({reason}). You can still copy Markdown and open the GitHub editor manually.",
  disconnect: "Sign out",
  connectLead:
    "Connect GitHub to open a PR from your fork of intuition-box/ideas.",
  connectButton: "Sign in with GitHub",
  forkLabel: "Fork",
  oauthErrorPrefix: "GitHub connection failed:",
} as const;
